name: Bug Report (T1)
description: Report a problem/bug with the T1-Theme.
title: "[Bug]: "
labels: [bug]
assignees:
  - Eight-P
  
body:

 # Info
 - type: markdown
    attributes:
      value: |
        "Please try and isolate the root cause of the issue as good as possible!
         (e.g. check you CustomCSS and disable any other Theme or Plugin)
         *If the issue is not caused by T1 alone, but in combination with another addon make sure to include that in the report!"

  # Main report
  - type: textarea
    attributes:
      label: "Please describe the issue in detail and how to reproduce it."
      description: "screenshots may help"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        "Please include as much information as possible."
      
  # T1 Version check
  - type: input
    attributes:
      label: "What’s your current T1 main and file version"
      description: "Main version: bottom of the Settings-menu sidebar | File version: Themes-tab card."

  # Discord client check
  - type: dropdown
    attributes:
      label: "What Discord client are you using?"
      description: "Info box at the bottom of the Settings-menu sidebar"
      multiple: true
      options:
        - Stable (Default)
        - PTB
        - Canary

  # Platform check 
  - type: dropdown
    attributes:
      label: "What Platform are you using?"
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - Browser (Web)
        - Other (list below)

  # Mod check 
  - type: dropdown
    attributes:
      label: "What Discord Mod are you using?"
      description: "Please note, the T1-Theme only officially supports BD (I'll try and help, but no guarantee)"
      multiple: true
      options:
        - BetterDiscord
        - Powercord
        - Vizality
        - GooseMod
        - Other (list below)

  # Additional notes
  - type: textarea
    attributes:
      label: "Any other additional notes."
      description: "(If you selected "other" above, you can list them here)"

  - type: markdown
  attributes:
    value: |
      "Thank you for taking the time to fill out this bug report"